[package]
name = "netpwn"
version = "1.0.0"
authors = ["styxs <styxs@styxs.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.0"
libc = "0.2"
which = "3.1.1"
